### ISSUE TITLE
performance issue: matchpattern_match blocks the browser for more than 1s at every URL change

### ISSUE THREAD

**Issue by maxlath** [99of9/Entity-Explosion#18]
## Environment
* addon version: v0.9.1
* browser: Firefox v102.0

## Issue
The addon blocks the browser for more than 1s at every URL change, as `matchpattern_match` runs its 5000+ regexes on the new URL. From the addon logs:
```
matchpattern_match false on about:addons took 1345ms
```
It might be that some of those regexes are particularly slow, or just that there are too many of them to run fast

**Comment by 99of9** [comment]
Thanks for letting me know. I haven't noticed this on Chrome, but will test it out on Firefox.

**Comment by 99of9** [comment]
I've just submitted version 0.9.5 to Firefox which will fix this issue. In testing I have a 100x speed increase on this matchpattern testing. Instead of running all 7000 matchpatterns, I filter them according to their hostname, and just run against the few that match the same host (usually 0 or 1, sometimes up to about 5).  Thanks so much for reporting and commenting @maxlath @lefuturiste and @JeanFred. Sorry it took so long to get around to this.

**Comment by lefuturiste** [comment]
> I've just submitted version 0.9.5 to Firefox which will fix this issue. In testing I have a 100x speed increase on this matchpattern testing. Instead of running all 7000 matchpatterns, I filter them according to their hostname, and just run against the few that match the same host (usually 0 or 1, sometimes up to about 5). Thanks so much for reporting and commenting @maxlath @lefuturiste and @JeanFred. Sorry it took so long to get around to this.

Thanks a lot, I will test this extension again.

**Comment by 99of9** [comment]
@lefuturiste Great. This should now be live in Firefox.  I'd appreciate any feedback about performance.
