### ISSUE TITLE
Question: What is the correct set up for JSON

### ISSUE THREAD

**Issue by salgo60** [99of9/Entity-Explosion#9]
If you go to page [en/article/NaimaSahlbom](https://www.skbl.se/en/article/NaimaSahlbom) and try  Entity Explosion I get two entries for **Svenskt kvinnobiografiskt lexikon** that is what I want

![image](https://user-images.githubusercontent.com/14206509/94689946-c3e76480-032f-11eb-9d0b-545def534054.png)
* SKBL page
  * english https://www.skbl.se/en/article/NaimaSahlbom
  * swedish https://www.skbl.se/sv/artikel/NaimaSahlbom
* SKBL Json page  https://www.skbl.se/en/article/NaimaSahlbom.json
* Wikidata property [Property:P4963](https://www.wikidata.org/wiki/Property:P4963)

**Question:**  
Have I set up [P4963](https://www.wikidata.org/wiki/Property:P4963) correct as you think we should to get the best usage of Entity Explorer??

**Comment by 99of9** [comment]
"Operator" is meant to say who is the Third Party supplying the Third-party formatter URL.  I've changed the qualifier to file format. With the current settings this probably actually hides the JSON link in EE (sorry!), because I thought users would rarely want to see the JSON if they were just clicking around.

**Comment by 99of9** [comment]
The English and Swedish looks good, and EE should send you to the right place depending on which language you've chosen in EE.

**Comment by salgo60** [comment]
Thanks for feedback
